print("     *\n", "   * *\n", "  *   *\n", " *     *\n", "***   ***\n",
      "  *   *\n", "  *   *\n", "   *   *\n", "  ***** \n")

print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")


print("         *")
print("        * *")
print("       *   *")
print("      *     *")
print("     *       *")
print("    *         *")
print("   *           *")
print("  *             *")
print(" *               *")
print("******       ******")
print("     *       *")
print("     *       *")
print("     *       *")
print("     *       *")
print("     *       *")
print("     *********")


print("         *", "         *", sep=" "*12)
print("        * *", "        * *", sep=" "*11)
print("       *   *", "       *   *", sep=" "*10)
print("      *     *", "      *     *", sep=" "*9)
print("     *       *", "     *       *", sep=" "*8)
print("    *         *", "    *         *", sep=" "*7)
print("   *           *", "   *           *", sep=" "*6)
print("  *             *", "  *             *", sep=" "*5)
print(" *               *", " *               *", sep=" "*4)
print("******       ******", "******       ******", sep=" "*3)
print("     *       *", "     *       *", sep=" "*8)
print("     *       *", "     *       *", sep=" "*8)
print("     *       *", "     *       *", sep=" "*8)
print("     *       *", "     *       *", sep=" "*8)
print("     *       *", "     *       *", sep=" "*8)
print("     *********", "     *********", sep=" "*8)
